In [1]:
# Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import geopandas as gpd
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Data import
data = pd.read_csv('GOI.csv')
data.head(10)

,Category,Country/ States/ Union Territories Name,Literacy Rate (Persons) - Total - 2001,Literacy Rate (Persons) - Total - 2011,Literacy Rate (Persons) - Rural - 2001,Literacy Rate (Persons) - Rural - 2011,Literacy Rate (Persons) - Urban - 2001,Literacy Rate (Persons) - Urban - 2011
0,Country,INDIA,64.8,73.0,58.7,67.8,79.9,84.1
1,State,Andhra Pradesh,60.5,67.0,54.5,60.4,76.1,80.1
2,State,Arunachal Pradesh,54.3,65.4,47.8,59.9,78.3,82.9
3,State,Assam,63.3,72.2,59.7,69.3,85.3,88.5
4,State,Bihar,47.0,61.8,43.9,59.8,71.9,76.9
5,State,Chhattisgarh,64.7,70.3,60.5,66.0,80.6,84.0
6,State,Goa,82.0,88.7,79.7,86.6,84.4,90.0
7,State,Gujarat,69.1,78.0,61.3,71.7,81.8,86.3
8,State,Haryana,67.9,75.6,63.2,71.4,79.2,83.1
9,State,Himachal Pradesh,76.5,82.8,75.1,81.9,88.9,91.1

## ***Questions to the data***
1. In 2011, which states and UTs were top in literacy rates
2. In 2011, which states and UTs were bottom in literacy rates
3. In 2011, Rural vs Urban literacy rates comparison in the states
4. Between 2001 and 2011, calculate improvements of states and UTs in overall literacy rates?

In [3]:
# Preprocessing
new_names = {'Country/ States/ Union Territories Name': 'Country/States/UTs', 'Literacy Rate (Persons) - Total - 2001': 'Literacy_total_2001', 'Literacy Rate (Persons) - Total - 2011': 'Literacy_total_2011', 'Literacy Rate (Persons) - Rural - 2001': 'Literacy_rural_2001', 'Literacy Rate (Persons) - Rural - 2011': 'Literacy_rural_2011', 'Literacy Rate (Persons) - Urban - 2001': 'Literacy_urban_2001', 'Literacy Rate (Persons) - Urban - 2011': 'Literacy_urban_2011'}
data = data.rename(columns = new_names)

data.loc[data['Country/States/UTs']=='Arunachal Pradesh','Country/States/UTs']='Arunanchal Pradesh'
data.loc[data['Country/States/UTs']=='D & N Haveli','Country/States/UTs']='Dadara & Nagar Havelli'
data.loc[data['Country/States/UTs']=='A & N Islands','Country/States/UTs']='Andaman & Nicobar Island'

In [4]:
data.head()

,Category,Country/States/UTs,Literacy_total_2001,Literacy_total_2011,Literacy_rural_2001,Literacy_rural_2011,Literacy_urban_2001,Literacy_urban_2011
0,Country,INDIA,64.8,73.0,58.7,67.8,79.9,84.1
1,State,Andhra Pradesh,60.5,67.0,54.5,60.4,76.1,80.1
2,State,Arunanchal Pradesh,54.3,65.4,47.8,59.9,78.3,82.9
3,State,Assam,63.3,72.2,59.7,69.3,85.3,88.5
4,State,Bihar,47.0,61.8,43.9,59.8,71.9,76.9

In [5]:
# New Dataframes
data_states = data[data['Category'] == 'State']
data_uts = data[data['Category'] == 'Union Territory']
data_states_uts=data.loc[data['Country/States/UTs']!='INDIA']
data_states_uts=data_states_uts.rename(columns={'Country/States/UTs':'States/UTs'})

In [6]:
# States Data(Overall, Rural, Urban,Rural-Urban)
state_overall_2011 = data_states.sort_values(by = 'Literacy_total_2011')[['Country/States/UTs', 'Literacy_total_2011']].rename(columns = {'Country/States/UTs': 'State', 'Literacy_total_2011': 'value'})
state_rural_2011 = data_states.sort_values(by = 'Literacy_rural_2011')[['Country/States/UTs', 'Literacy_rural_2011']].rename(columns = {'Country/States/UTs': 'State', 'Literacy_rural_2011': 'value'})
state_urban_2011 = data_states.sort_values(by = 'Literacy_urban_2011')[['Country/States/UTs', 'Literacy_urban_2011']].rename(columns = {'Country/States/UTs': 'State', 'Literacy_urban_2011': 'value'})
state_rural_urban_2011 = data_states.sort_values(by = 'Literacy_urban_2011')[['Country/States/UTs', 'Literacy_urban_2011','Literacy_rural_2011']].rename(columns = {'Country/States/UTs': 'State', 'Literacy_rural_2011': 'rural','Literacy_urban_2011': 'urban'})

In [7]:
# Color variables
purple=(0.4,0.2,0.8,0.8)
golden=(0.8,0.69,0.21,0.5)
grey=(0.1,0.1,0.1,0.2)
pink=(0.6,0.2,0.8,0.8)
blue=(0.3,0.2,0.9,0.9)

In [8]:
# Bar chart of literacy rates in states overall
# Uncomment the following lines
# fig,ax=plt.subplots(figsize=(10,7),layout='constrained')
# bars=ax.barh(state_overall_2011['State'], state_overall_2011['value'],color=purple)
# ax.bar_label(bars,labels=[str(datavalue)+'%' for datavalue in bars.datavalues])
# ax.set_xlim(right=max(state_overall_2011['value'])*1.1)
# ax.set_title('Literacy Rates of States Overall in 2011')
# ax.set_xlabel('Literacy Rates')
# ax.set_ylabel('States')
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)

In [9]:
# Bar chart of literacy rates in states rural
# Uncomment the following lines
# fig,ax=plt.subplots(figsize=(10,7),layout='constrained')
# bars=ax.barh(state_rural_2011['State'], state_rural_2011['value'],color=purple)
# ax.bar_label(bars,labels=[str(datavalue)+'%' for datavalue in bars.datavalues])
# ax.set_xlim(right=max(state_rural_2011['value'])*1.1)
# ax.set_title('Literacy Rates Rural in 2011')
# ax.set_xlabel('Literacy Rates')
# ax.set_ylabel('States')
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)

In [10]:
# Bar chart of literacy rates in states urban
# Uncomment the following lines
# fig,ax=plt.subplots(figsize=(10,7),layout='constrained')
# bars=ax.barh(state_urban_2011['State'], state_urban_2011['value'],color=purple)
# ax.bar_label(bars,labels=[str(datavalue)+'%' for datavalue in bars.datavalues])
# ax.set_xlim(right=max(state_urban_2011['value'])*1.1)
# ax.set_title('Literacy Rates Urban in 2011')
# ax.set_xlabel('Literacy Rates')
# ax.set_ylabel('States')
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)

In [11]:
# Split Bar chart of literacy rates in states rural vs urban comparison
# Uncomment the following lines
# fig,ax=plt.subplots(figsize=(12,10),layout='constrained')
# x=np.arange(data_states.shape[0])
# width=0.4
# bar1=ax.barh(x+width/2+0.02,state_rural_urban_2011['urban'],width,label='Urban',color=pink)
# bar2=ax.barh(x-width/2-0.02,state_rural_urban_2011['rural'],width,label='Rural',color=blue)
# ax.bar_label(bar1,labels=[str(datavalue)+'%' for datavalue in bar1.datavalues],fontsize=10)
# ax.bar_label(bar2,labels=[str(datavalue)+'%' for datavalue in bar2.datavalues],fontsize=8)
# ax.set_xlim(right=max(state_rural_urban_2011['urban'])*1.1)
# ax.set_title('Literacy Rates Rural vs Urban Comparison in 2011')
# ax.set_xlabel('Literacy Rates')
# ax.set_ylabel('States')
# ax.set_yticks(x)
# ax.set_yticklabels(state_rural_urban_2011['State'])
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)
# ax.legend()

In [12]:
# Bar chart of literacy rates in UTs overall
# Uncomment the following lines
# ut_overall_2011 = data_uts.sort_values(by = 'Literacy_total_2011')[['Country/States/UTs', 'Literacy_total_2011']].rename(columns = {'Country/States/UTs': 'UT', 'Literacy_total_2011': 'value'})
# fig,ax=plt.subplots(figsize=(8,4),layout='constrained')
# bars=ax.barh(ut_overall_2011['UT'], ut_overall_2011['value'],color=purple)
# ax.bar_label(bars,labels=[str(datavalue)+'%' for datavalue in bars.datavalues])
# ax.set_xlim(right=max(ut_overall_2011['value'])*1.1)
# ax.set_title('Literacy Rates of UTs Overall in 2011')
# ax.set_xlabel('Literacy Rates')
# ax.set_ylabel('UTs')
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)

In [13]:
# Creating colormap
purple_colors=[(255./255.,12./255.,255./255.,1.0),(156./255.,12./255.,156./255.,1.0),(94./255.,12./255.,94./255.,1.0)]
purple_cmap=mcolors.LinearSegmentedColormap.from_list('CustomPurple',purple_colors)

In [14]:
# Creating required data to plot Geo chart
states_uts_overall_2011 = data_states_uts.sort_values(by = 'Literacy_total_2011')[['States/UTs', 'Literacy_total_2011']].rename(columns = {'Literacy_total_2011': 'value'})

In [15]:
# Reading states and UTs in India
indian_states_df=gpd.read_file('Indian_states.shp')
indian_states_df['st_nm']=indian_states_df['st_nm'].str.strip()
merged_df=indian_states_df.merge(states_uts_overall_2011,left_on='st_nm',right_on='States/UTs',how='left')

In [16]:
# Geo chart of states and UTs with literacy rates in India
# Uncomment the following lines
# fig,ax=plt.subplots(1,figsize=(8,8))
# ax.axis('off')
# ax.set_title('Literacy Rates Overall in 2011 Across States and UTs',fontdict={'fontsize':'16','fontweight':'3'})
# fig.set_facecolor((0.8,0.69,0.21,0.5))
# ax=merged_df.plot(ax=ax,column='value',linewidth=0.8,edgecolor='0.8',legend=True,missing_kwds={'color':'lightgrey'},cmap=purple_cmap,legend_kwds={'shrink':0.8})
# for idx,row in merged_df.iterrows():
#   coords=row['geometry'].representative_point().coords[0]
#   state_name=row['st_nm']
#   state_value=row['value']
#   label_text=f'{state_value}%' if state_value==state_value else ''
#   ax.annotate(text=label_text,xy=coords,horizontalalignment='center',verticalalignment='center',fontsize=8,color='white',weight='bold')
# plt.tight_layout()

## ***We will calculate improvement in literacy rates from 2001 to 2011. To do that, we check what was the room for improvement in literacy rate in 2001, and how much improvement has actually happened in 2011 multiplied by 100 to convert the number in percentage. So the formula is:***

Improvement percentage=$\frac{(Literacy\ rate\ in\ 2011-Literacy\ rate\ in\ 2001)}{(100-Literacy\ rate\ in\ 2001)}$*100%

In [17]:
# Calculating improvement percentage of states
data_states['Improvement_percentage_total']=round((data_states['Literacy_total_2011']-data_states['Literacy_total_2001'])/(100.-data_states['Literacy_total_2001'])*100,2)

In [18]:
# Bar chart of improvements in States
# Uncomment the following lines
# state_improvement_total = data_states.sort_values(by = 'Improvement_percentage_total')[['Country/States/UTs', 'Improvement_percentage_total']].rename(columns = {'Country/States/UTs': 'State', 'Improvement_percentage_total': 'value'})
# fig,ax=plt.subplots(figsize=(10,7),layout='constrained')
# bars=ax.barh(state_improvement_total['State'], state_improvement_total['value'],color=purple)
# ax.bar_label(bars,labels=[str(datavalue)+'%' for datavalue in bars.datavalues])
# ax.set_xlim(right=max(state_improvement_total['value'])*1.1)
# ax.set_title('Literacy Improvement Percentage from 2001 to 2011 in States')
# ax.set_xlabel('Literacy Improvement Percentage')
# ax.set_ylabel('States')
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)

In [19]:
# Calculating improvement percentage of states
data_uts['Improvement_percentage_total']=round((data_uts['Literacy_total_2011']-data_uts['Literacy_total_2001'])/(100.-data_uts['Literacy_total_2001'])*100,2)

In [20]:
# Bar chart of improvements in UTs
# Uncomment the following lines
# ut_improvement_total = data_uts.sort_values(by = 'Improvement_percentage_total')[['Country/States/UTs', 'Improvement_percentage_total']].rename(columns = {'Country/States/UTs': 'UT', 'Improvement_percentage_total': 'value'})
# fig,ax=plt.subplots(figsize=(8,4),layout='constrained')
# bars=ax.barh(ut_improvement_total['UT'], ut_improvement_total['value'],color=purple)
# ax.bar_label(bars,labels=[str(datavalue)+'%' for datavalue in bars.datavalues])
# ax.set_xlim(right=max(ut_improvement_total['value'])*1.1)
# ax.set_title('Literacy Improvement Percentage from 2001 to 2011 in UTs')
# ax.set_xlabel('Literacy Improvement Percentage')
# ax.set_ylabel('UTs')
# fig.set_facecolor(grey)
# ax.set_facecolor(golden)